# Generated by Django 3.0.8 on 2020-07-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='invoice_recurring_advance',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
    ]
