# Generated by Django 3.0.8 on 2020-07-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tax_details',
            name='bills_terms',
            field=models.IntegerField(blank=True, choices=[(1, 'On Due Date'), (2, '10 Days'), (3, '20 Days'), (4, '30 Days'), (5, '60 Days'), (6, '90 Days'), (7, 'Custom')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_tax_details',
            name='invoice_terms',
            field=models.IntegerField(blank=True, choices=[(1, 'On Due Date'), (2, '10 Days'), (3, '20 Days'), (4, '30 Days'), (5, '60 Days'), (6, '90 Days'), (7, 'Custom')], db_index=True, null=True),
        ),
    ]
