# Generated by Django 3.1 on 2020-09-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnode',
            name='cgst_12',
        ),
        migrations.RemoveField(
            model_name='creditnode',
            name='cgst_18',
        ),
        migrations.RemoveField(
            model_name='creditnode',
            name='cgst_28',
        ),
        migrations.RemoveField(
            model_name='creditnode',
            name='cgst_5',
        ),
        migrations.RemoveField(
            model_name='creditnode',
            name='cgst_other',
        ),
        migrations.RemoveField(
            model_name='creditnode',
            name='igst_12',
        ),
        migrations.RemoveField(
            model_name='creditnode',
            name='igst_18',
        ),
        migrations.RemoveField(
            model_name='creditnode',
            name='igst_28',
        ),
        migrations.RemoveField(
            model_name='creditnode',
            name='igst_5',
        ),
        migrations.RemoveField(
            model_name='creditnode',
            name='igst_other',
        ),
        migrations.RemoveField(
            model_name='creditnode',
            name='sgst_12',
        ),
        migrations.RemoveField(
            model_name='creditnode',
            name='sgst_18',
        ),
        migrations.RemoveField(
            model_name='creditnode',
            name='sgst_28',
        ),
        migrations.RemoveField(
            model_name='creditnode',
            name='sgst_5',
        ),
        migrations.RemoveField(
            model_name='creditnode',
            name='sgst_other',
        ),
        migrations.AddField(
            model_name='creditnote_items',
            name='is_blank_credit',
            field=models.CharField(blank=True, choices=[('off', 'off'), ('on', 'on')], db_index=True, default='off', max_length=4, null=True),
        ),
    ]
