# Generated by Django 3.1 on 2020-09-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='inovice_over_due_count',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
