# Generated by Django 3.1 on 2020-10-10 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='product_category',
            field=models.IntegerField(blank=True, choices=[(1, 'Raw Material'), (2, 'Finished Goods'), (3, 'Consumable & Stores')], db_index=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='QuotationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('cc_email', models.CharField(blank=True, max_length=500, null=True)),
                ('quotation_referance', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('quotation_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('quotation_check', models.CharField(blank=True, choices=[('off', 'off'), ('on', 'on')], db_index=True, default='off', max_length=4, null=True)),
                ('save_type', models.IntegerField(choices=[(1, 'save_send'), (2, 'save_close'), (3, 'save_draft'), (4, 'save_print'), (5, 'save_new')], db_index=True, default=2)),
                ('quotation_date', models.DateField(db_index=True)),
                ('invoice_state_supply', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('terms_and_condition', models.CharField(blank=True, db_index=True, max_length=400, null=True)),
                ('Note', models.CharField(blank=True, db_index=True, max_length=400, null=True)),
                ('attachements', models.FileField(blank=True, db_index=True, null=True, upload_to='')),
                ('sub_total', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('total_discount', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('shipping_charges', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('total_amount', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('is_cs_gst', models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True, null=True)),
                ('cgst', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('sgst', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('igst', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('quotation_org_gst_num', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('qutotation_org_gst_type', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('quotation_org_gst_state', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('quotation_delete_status', models.IntegerField(db_index=True, default=0)),
                ('quotation_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.contacts')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'quotation_tbl',
            },
        ),
        migrations.CreateModel(
            name='Quotation_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_header', models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True, null=True)),
                ('header_name', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('header_number_count', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('header_subtotal', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('description', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('price', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('discount_type', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('discount', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('tax', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('tax_amount', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('cgst_amount', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('sgst_amount', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('igst_amount', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('amount', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('amount_inc', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.accgroups')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.productsmodel')),
                ('quotation_item_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.quotationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'quotation_items_tbl',
            },
        ),
    ]
