# Generated by Django 3.1 on 2020-09-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_invoicemodel_inovice_over_due_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='inovice_over_due_count',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
