# Generated by Django 3.0.8 on 2020-08-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200807_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicemodel',
            name='is_active',
        ),
        migrations.AddField(
            model_name='creditnode',
            name='creditnote_delete_status',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='invoice_delete_status',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_delete_status',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
