# Generated by Django 3.1 on 2020-09-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200923_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote_items',
            name='is_blank_credit',
        ),
        migrations.AddField(
            model_name='creditnode',
            name='is_blank_credit',
            field=models.CharField(blank=True, choices=[('off', 'off'), ('on', 'on')], db_index=True, default='off', max_length=4, null=True),
        ),
    ]
