# Generated by Django 3.0.8 on 2020-07-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200716_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='is_cs_gst',
            field=models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True, null=True),
        ),
    ]
