# Generated by Django 3.1 on 2020-10-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201010_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisations',
            old_name='debit_note',
            new_name='quotation_note',
        ),
        migrations.RenameField(
            model_name='organisations',
            old_name='debit_terms_and_condition',
            new_name='quotation_terms_and_condition',
        ),
    ]
