# Generated by Django 3.0.8 on 2020-08-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200803_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='note',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
    ]
