# Generated by Django 3.0.8 on 2020-07-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200727_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_status',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, 'Drafted'), (2, 'Cancelled'), (3, 'Send Mail')], db_index=True, default=0, null=True),
        ),
    ]
