# Generated by Django 3.0.8 on 2020-08-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_organisations_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='save_type',
            field=models.IntegerField(choices=[(1, 'save_send'), (2, 'save_close'), (3, 'save_draft'), (4, 'save_print'), (5, 'void')], db_index=True, default=2),
        ),
    ]
