# Generated by Django 3.1 on 2020-10-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201012_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationmodel',
            name='quotation_expire_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
