# Generated by Django 3.0.8 on 2020-07-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_purchaseorder_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tax_details',
            name='default_gstin',
            field=models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False, null=True),
        ),
    ]
