# Generated by Django 3.1 on 2020-09-23 08:42

import app.models.contacts_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20200923_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_note_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('debit_note_check', models.CharField(blank=True, choices=[('off', 'off'), ('on', 'on')], db_index=True, default='off', max_length=4, null=True)),
                ('save_type', models.IntegerField(choices=[(1, 'save_close'), (2, 'save_draft')], db_index=True, default=1)),
                ('debit_note_date', models.DateField(db_index=True)),
                ('debit_note_refrence', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('debit_note_pay_terms', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('debit_note_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('Note', models.CharField(blank=True, db_index=True, max_length=400, null=True)),
                ('attachements', models.FileField(blank=True, db_index=True, null=True, upload_to=app.models.contacts_model.attachments_rename)),
                ('sub_total', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('total_discount', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('total', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('balance_due', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('total_balance', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('freight_charges', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('cgst', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('sgst', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('igst', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('is_cs_gst', models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True, null=True)),
                ('debit_org_gst_num', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('debit_org_gst_type', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('debit_org_gst_state', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('debit_delete_status', models.IntegerField(db_index=True, default=0)),
                ('entry_status', models.IntegerField(blank=True, choices=[(0, 'Due'), (1, 'Over Due By'), (2, 'Drafted'), (3, 'Paid'), (4, 'Partially Paid')], db_index=True, null=True)),
                ('entry_date_count', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.contacts')),
            ],
            options={
                'verbose_name_plural': 'purchase_entry_tbl',
            },
        ),
        migrations.CreateModel(
            name='DebitNoteItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('price', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('discount_type', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('discount', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('tax', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('cgst_amount', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('sgst_amount', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('igst_amount', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('amount', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('amount_inc', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.accgroups')),
                ('debit_note_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.debitnote')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.productsmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'purchase_entry_items_tbl',
            },
        ),
    ]
