# Generated by Django 3.0 on 2020-07-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_invoicemodel_is_cs_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_line_items',
            name='amount_inc',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='cgst',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='igst',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='sgst',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
