# Generated by Django 3.1 on 2020-09-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_debitnote_debitnoteitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='debit_note',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='organisations',
            name='debit_terms_and_condition',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
    ]
