# Generated by Django 3.1 on 2020-08-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200808_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address_details',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='user_tax_details',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True),
        ),
    ]
