# Generated by Django 3.1 on 2020-10-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_quotationmodel_quotation_expire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationmodel',
            old_name='invoice_state_supply',
            new_name='quotation_state_supply',
        ),
    ]
