# Generated by Django 3.0.8 on 2020-08-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200804_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_delivery_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
