# Generated by Django 3.1 on 2020-09-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200902_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='invoice_recurring_pay',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
