# Generated by Django 3.1 on 2020-09-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200923_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debitnote',
            old_name='debit_note_pay_terms',
            new_name='attention',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='attachements',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='debit_note_due_date',
        ),
        migrations.AddField(
            model_name='debitnote',
            name='contact_number',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='customer',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='debit_delivery_address',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='is_customer_delivary',
            field=models.CharField(choices=[('off', 'off'), ('on', 'on')], db_index=True, default='off', max_length=4),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='is_organisation_delivary',
            field=models.CharField(choices=[('off', 'off'), ('on', 'on')], db_index=True, default='off', max_length=4),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='terms_and_condition',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
    ]
