# Generated by Django 3.1 on 2020-09-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_invoicemodel_invoice_recurring_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseentry',
            name='purchase_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Due'), (1, 'Over Due By'), (2, 'Drafted'), (3, 'Paid'), (3, 'Partially Paid')], db_index=True, null=True),
        ),
    ]
