# Generated by Django 3.1 on 2020-08-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200811_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='tds',
            field=models.CharField(blank=True, db_index=True, default=0.0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(0, 'KG'), (1, 'G'), (2, 'OZ'), (3, 'LB'), (4, 'T'), (5, 'MT'), (6, 'CT'), (7, 'FURLONG'), (8, 'IN'), (9, 'FT'), (10, 'YD'), (11, 'MI'), (12, 'M'), (13, 'ML'), (14, 'SF'), (15, 'SQ'), (16, 'CM'), (17, 'BKT'), (18, 'BAG'), (19, 'BOWL'), (20, 'BX'), (21, 'CARD'), (22, 'CASE'), (23, 'CARTON'), (24, 'DZ'), (25, 'EA'), (26, 'GAL'), (27, 'GS'), (28, 'KIT'), (29, 'SET'), (30, 'SHT'), (31, 'TUBE'), (32, 'PK'), (31, 'TB'), (33, 'TSP'), (34, 'C'), (35, 'PT'), (36, 'QT'), (37, 'ML'), (38, 'L')], db_index=True, null=True),
        ),
    ]
