# Generated by Django 3.1 on 2020-09-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200923_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitnote',
            name='balance_due',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='freight_charges',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='total_balance',
        ),
    ]
