# Generated by Django 3.1 on 2020-10-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201012_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_terms',
            field=models.IntegerField(blank=True, choices=[(1, 'Due Immediately'), (2, '10 Days'), (3, '20 Days'), (4, '30 Days'), (5, '60 Days'), (6, '90 Days')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_tax_details',
            name='bills_terms',
            field=models.IntegerField(blank=True, choices=[(1, 'Due Immediately'), (2, '10 Days'), (3, '20 Days'), (4, '30 Days'), (5, '60 Days'), (6, '90 Days')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_tax_details',
            name='invoice_terms',
            field=models.IntegerField(blank=True, choices=[(1, 'Due Immediately'), (2, '10 Days'), (3, '20 Days'), (4, '30 Days'), (5, '60 Days'), (6, '90 Days')], db_index=True, null=True),
        ),
    ]
