# Generated by Django 3.1 on 2020-09-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200923_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debitnote',
            options={'verbose_name_plural': 'debit_note_tbl'},
        ),
        migrations.AlterModelOptions(
            name='debitnoteitems',
            options={'verbose_name_plural': 'debit_note_items_tbl'},
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='entry_date_count',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='entry_status',
        ),
    ]
