# Generated by Django 3.1 on 2020-09-07 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_purchaseentry_purchase_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='purchase_status',
            new_name='entry_status',
        ),
    ]
