# Generated by Django 3.1 on 2020-10-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201013_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationmodel',
            name='quotation_pay_terms',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
