# Generated by Django 3.1 on 2020-09-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200923_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='hsn_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
