# Generated by Django 3.1 on 2020-09-07 06:50

import app.models.contacts_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20200907_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('payment_number_check', models.CharField(blank=True, choices=[('off', 'off'), ('on', 'on')], db_index=True, default='off', max_length=4, null=True)),
                ('save_type', models.IntegerField(choices=[(1, 'save_close'), (2, 'save_draft')], db_index=True, default=1)),
                ('payment_date', models.DateField(db_index=True)),
                ('payment_reference', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('payment_mode', models.IntegerField(blank=True, choices=[(0, 'Any'), (1, 'Cash'), (2, 'Card'), (3, 'Cheque'), (4, 'Net Banking')], db_index=True, null=True)),
                ('Note', models.CharField(blank=True, db_index=True, max_length=400, null=True)),
                ('attachements', models.FileField(blank=True, db_index=True, null=True, upload_to=app.models.contacts_model.attachments_rename)),
                ('Amount', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('purchase_entry_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.purchaseentry')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.contacts')),
            ],
            options={
                'verbose_name_plural': 'payment_made_tbl',
            },
        ),
    ]
