# Generated by Django 3.1 on 2020-08-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200817_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='product_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
