# Generated by Django 3.1 on 2020-10-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_quotationmodel_is_invoice_creted'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationmodel',
            name='quotation_salesperson',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
