# Generated by Django 3.1 on 2020-09-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_purchasepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseentry',
            name='date_count',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseentry',
            name='entry_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Due'), (1, 'Over Due By'), (2, 'Drafted'), (3, 'Paid'), (4, 'Partially Paid')], db_index=True, null=True),
        ),
    ]
