# Generated by Django 3.1 on 2020-09-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200925_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_purchase_entry_maked',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
