# Generated by Django 3.1 on 2020-10-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_quotationmodel_quotation_salesperson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationmodel',
            old_name='qutotation_org_gst_type',
            new_name='quotation_org_gst_type',
        ),
    ]
