# Generated by Django 3.1 on 2020-09-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200907_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseentry',
            old_name='date_count',
            new_name='entry_date_count',
        ),
    ]
