# Generated by Django 3.1 on 2020-08-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200819_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address_details',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_address_details',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_address_details',
            name='flat_no',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_address_details',
            name='pincode',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_address_details',
            name='street',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
