# Generated by Django 3.1 on 2020-09-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_purchaseorder_is_purchase_entry_maked'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='unused_credit',
            field=models.CharField(blank=True, db_index=True, default=0.0, max_length=20, null=True),
        ),
    ]
