# Generated by Django 3.1 on 2020-09-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200907_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseentry',
            name='total',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
