# Generated by Django 3.0.7 on 2020-08-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200819_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='selling_tax',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
