# Generated by Django 3.1 on 2020-08-20 07:14

import app.models.contacts_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_auto_20200819_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_entry_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('purchase_number_check', models.CharField(blank=True, choices=[('off', 'off'), ('on', 'on')], db_index=True, default='off', max_length=4, null=True)),
                ('save_type', models.IntegerField(choices=[(1, 'save_send'), (2, 'save_close'), (3, 'save_draft'), (4, 'save_print'), (5, 'void')], db_index=True, default=2)),
                ('purchase_entry_date', models.DateField(db_index=True)),
                ('purchase_entry_refrence', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('purchase_entry_pay_terms', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('purchase_entry_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('Note', models.CharField(blank=True, db_index=True, max_length=400, null=True)),
                ('attachements', models.FileField(blank=True, db_index=True, null=True, upload_to=app.models.contacts_model.attachments_rename)),
                ('sub_total', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('total_discount', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('advance', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('total_balance', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('cgst', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('sgst', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('igst', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.contacts')),
            ],
        ),
    ]
