# Generated by Django 3.1 on 2020-09-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_contacts_unused_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='unused_credit',
            field=models.CharField(blank=True, db_index=True, default='0.00', max_length=20, null=True),
        ),
    ]
