# Generated by Django 3.1 on 2020-09-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_purchaseentry_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseentry',
            name='balance_due',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
