# Generated by Django 3.1 on 2020-10-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201013_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationmodel',
            name='is_quotation_expire',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
