# Generated by Django 3.1 on 2020-09-08 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_purchaseentry_balance_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseentry',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.purchaseorder'),
        ),
    ]
