# Generated by Django 3.1 on 2020-08-20 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_purchaseentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseentry',
            options={'verbose_name_plural': 'purchase_entry_tbl'},
        ),
        migrations.CreateModel(
            name='PurchaseEntryItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('price', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('discount_type', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('discount', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('tax', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('tax_amount', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('cgst_amount', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('sgst_amount', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('igst_amount', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('amount', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('amount_inc', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.accgroups')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.productsmodel')),
                ('purchase_entry_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.purchaseentry')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'purchase_entry_items_tbl',
            },
        ),
    ]
