# Generated by Django 3.1 on 2020-09-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_purchaseentry_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_mode',
            field=models.IntegerField(blank=True, choices=[(1, 'Cash'), (2, 'Card'), (3, 'Cheque'), (4, 'Demand Draft'), (5, 'Net Banking')], db_index=True, null=True),
        ),
    ]
