# Generated by Django 3.1 on 2020-09-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200926_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnote',
            name='purchase_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.purchaseentry'),
        ),
    ]
