# Generated by Django 3.1 on 2020-09-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200908_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
