# Generated by Django 3.1 on 2020-09-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200908_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_org_gst_num',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_org_gst_state',
            field=models.CharField(blank=True, db_index=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_org_gst_type',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
    ]
