# Generated by Django 3.1 on 2020-09-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_debitnote_purchase_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnote',
            name='debit_delivery_address',
            field=models.TextField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_address',
            field=models.TextField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
