# Generated by Django 3.1 on 2020-09-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200928_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseentry',
            name='debit_note',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
