# Generated by Django 3.1 on 2020-09-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200910_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_advance_make_pay',
            field=models.CharField(blank=True, choices=[('off', 'off'), ('on', 'on')], db_index=True, default='off', max_length=4, null=True),
        ),
    ]
