# Generated by Django 3.1 on 2020-09-15 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_purchaseorder_order_advance_make_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.accgroups'),
        ),
    ]
