# Generated by Django 3.1 on 2020-10-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_purchaseentry_debit_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote_items',
            name='product_type',
        ),
        migrations.AddField(
            model_name='creditnote_items',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.accgroups'),
        ),
    ]
