# Generated by Django 3.1 on 2020-10-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20201001_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='total',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
