# Generated by Django 3.1 on 2020-09-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200916_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='customer_type',
            field=models.IntegerField(blank=True, choices=[(1, 'CUSTOMER'), (2, 'VENDOR'), (3, 'EMPLOYEE'), (4, 'CUSTOMER AND VENDOR')], db_index=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='customer_type',
            field=models.IntegerField(blank=True, choices=[(1, 'CUSTOMER'), (2, 'VENDOR'), (3, 'EMPLOYEE'), (4, 'CUSTOMER AND VENDOR')], db_index=True, default=1),
        ),
    ]
