# Generated by Django 3.1 on 2020-10-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_purchaseorder_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='customer_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Customer'), (2, 'Vendor'), (3, 'Employee'), (4, 'Customer and Vendor')], db_index=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='customer_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Customer'), (2, 'Vendor'), (3, 'Employee'), (4, 'Customer and Vendor')], db_index=True, default=1),
        ),
    ]
