# Generated by Django 3.1 on 2020-10-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201002_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='product_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Goods'), (1, 'Services'), (2, 'Bundle')], db_index=True, default=0, null=True),
        ),
    ]
