# Generated by Django 3.1 on 2020-10-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20201002_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_tax_details',
            name='preferred_delivery',
        ),
    ]
