# Generated by Django 3.1 on 2020-09-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200916_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account_details',
            name='account_holder_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_account_details',
            name='account_number',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user_account_details',
            name='bank_branch_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_account_details',
            name='bank_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
