# Generated by Django 3.1 on 2020-10-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_user_tax_details_preferred_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryproduct',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(0, 'Box'), (1, 'Cm'), (2, 'Dz'), (3, 'In'), (4, 'G'), (5, 'Ft'), (6, 'Kg'), (7, 'Km'), (8, 'Lb'), (9, 'Mg'), (10, 'M'), (11, 'Pcs')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(0, 'Box'), (1, 'Cm'), (2, 'Dz'), (3, 'In'), (4, 'G'), (5, 'Ft'), (6, 'Kg'), (7, 'Km'), (8, 'Lb'), (9, 'Mg'), (10, 'M'), (11, 'Pcs')], db_index=True, null=True),
        ),
    ]
