# Generated by Django 3.1 on 2020-09-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200916_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='purchase_account',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
