# Generated by Django 3.1 on 2020-09-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200916_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='purchase_tax',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
