# Generated by Django 3.1 on 2020-09-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200916_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='purchase_tax',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='selling_tax',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
