# Generated by Django 3.1 on 2020-10-03 05:41

import app.models.invoice_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20201002_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_terms',
            field=models.IntegerField(blank=True, choices=[(1, 'Due Immediately'), (2, '10 Days'), (3, '20 Days'), (4, '30 Days'), (5, '60 Days'), (6, '90 Days'), (7, 'Custom')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='attachements',
            field=models.FileField(blank=True, db_index=True, null=True, upload_to=app.models.invoice_model.attachments_rename),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='invoice_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Due'), (1, 'Over Due By'), (2, 'Paid')], db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user_tax_details',
            name='bills_terms',
            field=models.IntegerField(blank=True, choices=[(1, 'Due Immediately'), (2, '10 Days'), (3, '20 Days'), (4, '30 Days'), (5, '60 Days'), (6, '90 Days'), (7, 'Custom')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_tax_details',
            name='invoice_terms',
            field=models.IntegerField(blank=True, choices=[(1, 'Due Immediately'), (2, '10 Days'), (3, '20 Days'), (4, '30 Days'), (5, '60 Days'), (6, '90 Days'), (7, 'Custom')], db_index=True, null=True),
        ),
    ]
