# Generated by Django 3.1 on 2020-10-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20201003_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='organization_type',
            field=models.IntegerField(choices=[(1, 'Individual'), (2, 'Proprietorship'), (4, 'Partnership'), (5, 'Trust'), (6, 'Private Limited'), (7, 'Public Limited'), (8, 'Overseas Organisation'), (9, 'Government Organisation'), (10, 'Others')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='organisation_type',
            field=models.IntegerField(choices=[(1, 'Individual'), (2, 'Proprietorship'), (4, 'Partnership'), (5, 'Trust'), (6, 'Private Limited'), (7, 'Public Limited'), (8, 'Overseas Organisation'), (9, 'Government Organisation'), (10, 'Others')], db_index=True, default=1),
        ),
    ]
