# Generated by Django 3.0.6 on 2020-05-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='contact_name',
            new_name='vendor',
        ),
    ]
