# Generated by Django 3.0.6 on 2020-05-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200528_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_number_check',
            field=models.CharField(blank=True, choices=[('off', 'off'), ('on', 'on')], db_index=True, default='off', max_length=4, null=True),
        ),
    ]
