# Generated by Django 3.0.4 on 2020-06-01 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200601_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_address_details',
            name='organisation_cin',
        ),
        migrations.RemoveField(
            model_name='user_address_details',
            name='organisation_pan',
        ),
        migrations.AddField(
            model_name='user_address_details',
            name='organisation_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User_Tax_Details'),
        ),
    ]
