# Generated by Django 3.0.4 on 2020-06-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200601_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisations',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organisations',
            name='country',
        ),
        migrations.RemoveField(
            model_name='organisations',
            name='flat_no',
        ),
        migrations.RemoveField(
            model_name='organisations',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='organisations',
            name='state',
        ),
        migrations.RemoveField(
            model_name='organisations',
            name='street',
        ),
    ]
