# Generated by Django 3.0.6 on 2020-06-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200602_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='purchase_note',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='organisations',
            name='purchase_terms_and_condition',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True),
        ),
    ]
