# Generated by Django 3.0.7 on 2020-06-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200603_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='advacne_payemtn_method',
            new_name='advacne_payment_method',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='advacne_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
