# Generated by Django 3.0.7 on 2020-06-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_purchaseorder_gst_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='advacne_payment_method',
            field=models.CharField(blank=True, choices=[(1, 'Cash'), (2, 'Card'), (3, 'Cheque'), (4, 'Demand Draft'), (5, 'Net Banking')], db_index=True, max_length=5, null=True),
        ),
    ]
