# Generated by Django 3.0.7 on 2020-06-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200605_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='advance_payment_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
