# Generated by Django 3.0.7 on 2020-06-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicemodel',
            name='invoice_customer_mail',
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='cc_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
