# Generated by Django 3.0.6 on 2020-05-28 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200528_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='billing_address',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='purchase_number',
            new_name='purchase_order_number',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='adjustment',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='customer',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_customer_delivary',
            field=models.CharField(choices=[('off', 'off'), ('on', 'on')], db_index=True, default='off', max_length=4),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_organisation_delivary',
            field=models.CharField(choices=[('off', 'off'), ('on', 'on')], db_index=True, default='off', max_length=4),
        ),
        migrations.AlterField(
            model_name='purchase_items',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.AccGroups'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='contact_number',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
