# Generated by Django 3.0.7 on 2020-07-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200630_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='invoice_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Enum - Due'), (1, 'Expired'), (2, 'paid'), (3, 'partially paid')], db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='save_type',
            field=models.IntegerField(choices=[(1, 'save_send'), (2, 'save_close'), (3, 'save_draft'), (4, 'save_print'), (5, 'save_new')], db_index=True, default=2),
        ),
    ]
