# Generated by Django 3.0.4 on 2020-05-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200528_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address_details',
            name='default_address',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False),
        ),
    ]
