# Generated by Django 3.0.6 on 2020-06-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200601_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address_details',
            name='default_address',
            field=models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False, null=True),
        ),
    ]
