# Generated by Django 3.0.7 on 2020-06-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200604_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='gst_type',
        ),
    ]
