# Generated by Django 3.0.7 on 2020-06-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_purchaseorder_gst_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='advance_payment_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
