# Generated by Django 3.0.7 on 2020-06-10 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_customizemodulename'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeContactView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_org_name', models.IntegerField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False, null=True)),
                ('contact_email', models.IntegerField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False, null=True)),
                ('contact_phone', models.IntegerField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False, null=True)),
                ('customize_view_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CustomizeModuleName')),
            ],
        ),
    ]
