# Generated by Django 3.0.7 on 2020-06-10 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_customizecontactview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizePurchaseView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_reference', models.IntegerField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False, null=True)),
                ('purchase_vendor', models.IntegerField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False, null=True)),
                ('purchase_total', models.IntegerField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False, null=True)),
                ('customize_view_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CustomizeModuleName')),
            ],
        ),
        migrations.CreateModel(
            name='CustomizeProductView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_hsn', models.IntegerField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False, null=True)),
                ('product_description', models.IntegerField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False, null=True)),
                ('product_selling_price', models.IntegerField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False, null=True)),
                ('product_Purchase_price', models.IntegerField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False, null=True)),
                ('customize_view_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CustomizeModuleName')),
            ],
        ),
        migrations.CreateModel(
            name='CustomizeCreditView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_reference', models.IntegerField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False, null=True)),
                ('credit_date', models.IntegerField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False, null=True)),
                ('credit_amount', models.IntegerField(blank=True, choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=False, null=True)),
                ('customize_view_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CustomizeModuleName')),
            ],
        ),
    ]
