# Generated by Django 3.0.7 on 2020-06-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_customizecreditview_customizeproductview_customizepurchaseview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizepurchaseview',
            name='purchase_total',
        ),
    ]
