# Generated by Django 3.0.7 on 2020-06-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_customizepurchaseview_purchase_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizepurchaseview',
            name='purchase_total',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=0, null=True),
        ),
    ]
