# Generated by Django 3.0.7 on 2020-06-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200611_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeExpenseView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_vendor', models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=0, null=True)),
                ('expense_amount', models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=0, null=True)),
                ('expeanse_method', models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=0, null=True)),
                ('customize_view_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CustomizeModuleName')),
            ],
        ),
    ]
