# Generated by Django 3.0.2 on 2020-06-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_customizeexpenseview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customizeexpenseview',
            old_name='expeanse_method',
            new_name='expense_method',
        ),
    ]
