# Generated by Django 3.0.7 on 2020-06-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20200612_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizecontactview',
            name='contact_name',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customizecreditview',
            name='credit_name',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customizecreditview',
            name='credit_note',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customizeproductview',
            name='product_name',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customizeproductview',
            name='product_sku',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customizeproductview',
            name='product_type',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customizepurchaseview',
            name='purchase_date',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customizepurchaseview',
            name='purchase_number',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=0, null=True),
        ),
    ]
