# Generated by Django 3.0.7 on 2020-06-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200615_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizepurchaseview',
            name='purchase_status',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=0, null=True),
        ),
    ]
