# Generated by Django 3.0.7 on 2020-06-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_customizepurchaseview_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizeexpenseview',
            name='expense_date',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customizeexpenseview',
            name='expense_payment',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customizeexpenseview',
            name='expense_vocher',
            field=models.IntegerField(blank=True, choices=[(1, 'YES'), (0, 'NO')], db_index=True, default=0, null=True),
        ),
    ]
