# Generated by Django 3.0.7 on 2020-06-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_organisationgstsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tax_details',
            name='composite_gst',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user_tax_details',
            name='is_organisation_gst_register',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user_tax_details',
            name='multiple_gst',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
    ]
